### ISSUE TITLE
Shape Key Animations

### ISSUE THREAD

**Issue by mrdoob** [KhronosGroup/glTF-Blender-Exporter#48]
I seem to be unable to export Shape Key Animations (Morph Targets)...

Here's blend file and the exported glb missing animation: [flamingo.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1157971/flamingo.zip)
Interestingly, if the model has multi materials, the exported glb has animation: [flamingo_color.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1157972/flamingo_color.zip)

https://gltf-viewer.donmccurdy.com/ seems to have issues displaying it.

![screen shot 2017-07-18 at 21 08 34](https://user-images.githubusercontent.com/97088/28350384-77551418-6bfd-11e7-88eb-8871365ed410.png)

Not sure if it's a exporter issue or a loader issue. The resulting glb seems a bit too big though (4.6mb).

**Comment by UX3D-nopper** [comment]
Let me check ...

**Comment by UX3D-nopper** [comment]
Marked it as a bug. Let me dig into it.

**Comment by UX3D-nopper** [comment]
One thing I recognized:
The model has 14 morph targets, meaning 14 * 3 (POSITION, NORMAL, TANGENT) = 42 vertex input attributes (if you implement it like this) for just the morph targets. Can your engine handle and GPU handle this?

**Comment by mrdoob** [comment]
The model/animation was originaly done for http://www.ro.me/tech/ which only morphed positions. Is there a way to only include positions in the morph?

**Comment by UX3D-nopper** [comment]
At the moment, no - but let me fix this.

**Comment by UX3D-nopper** [comment]
During export, it can be selected, which morph target attributes should be exported.
https://github.com/KhronosGroup/glTF-Blender-Exporter

**Comment by UX3D-nopper** [comment]
Normally I can test this easily with my Vulkan engine, but I just implemented the required amount of MORPH targets (see implementation note):
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#morph-targets

**Comment by mrdoob** [comment]
![screen shot 2017-07-18 at 23 08 16](https://user-images.githubusercontent.com/97088/28352940-1309cb64-6c0e-11e7-9556-425ea329f5c5.png)

Getting there...? 😁

`flamingo_color.glb` went from 4.6mb to 1.8mb

Any ideas why `flamingo.glb` is missing the animation?

**Comment by UX3D-nopper** [comment]
I think for some reason the buffer offsets are not correct. I found something.

**Comment by UX3D-nopper** [comment]
Okay, the offset was a problem with my engine, as I am now supporting some more morph targets :-)

Can we try out a little example? The follwoing morphing triangle runs fine with my engine. When I drop it intos Don's viewer, there are no animations:
[01_morphed_triangle.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1158226/01_morphed_triangle.zip)
Can you tell me, why this happens on this viewers side?

The Blender file is included in the exporter.

**Comment by mrdoob** [comment]
![screen shot 2017-07-18 at 23 49 38](https://user-images.githubusercontent.com/97088/28354214-d6ab67a8-6c13-11e7-885f-95b20312b38d.png)

/cc @donmccurdy

**Comment by UX3D-nopper** [comment]
To summarize, either the three.js glTF 2.0 loader and/or viewer is doing something wrong
or
the Blender glTF 2.0 export is somehow wrong but my engine still can somehow import it.

I will cross check, if the exported animation data for morph targets is correct.

**Comment by mrdoob** [comment]
Your engine loads `flamingo.glb` (81KB) and plays the animation correctly?

**Comment by UX3D-nopper** [comment]
My engine cannot handle so much morph targets (14), I just increased the count to be 100% glTF 2.0 compliant.
Let's cross check, if how the other engines (CESIUM, Babylon, etc.) react on this file.

**Comment by mrdoob** [comment]
![screen shot 2017-07-19 at 00 31 55](https://user-images.githubusercontent.com/97088/28355665-d3cd9302-6c19-11e7-8cf0-33351794c965.png)

![screen shot 2017-07-19 at 00 32 41](https://user-images.githubusercontent.com/97088/28355675-da174730-6c19-11e7-9200-fcc19c7378b6.png)

My suspicion is that, for some reason, the exporter is not including morph targets when exporting `flamingo.blend`.

**Comment by UX3D-nopper** [comment]
Think I found the problem.

**Comment by UX3D-nopper** [comment]
Okay, I fixed a problem, where the animation data was sampled, even when it did only contain LINEAR data. This explains the arge size.
But, still no movement.
Strange thing is, that my engine can run the Khronos sample model (AnimatedMorphCube) without any problems. Also, it can run the exported ones from Blender.

![grafik](https://user-images.githubusercontent.com/27856744/28361124-ff044882-6c77-11e7-87a2-be2a67eb5e0b.png)

**Comment by UX3D-nopper** [comment]
Okay, there is a bug in the viewer/your engine:

I have modified the sample model, which does run on both engines - in its original form:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube

If I remove the animations and modify the weight in the mesh, I do get the following output in my engine, which is in my opinion correct:

![grafik](https://user-images.githubusercontent.com/27856744/28364808-687055fa-6c86-11e7-8ff4-470cce4877f3.png)

The viewers output is:

![grafik](https://user-images.githubusercontent.com/27856744/28364986-022c7200-6c87-11e7-9794-34ad63eb870f.png)

I changed both weights from 0.0 to 0.5.

Can you guys please check? I am setting this on wontfix for now.

```
{
  "accessors": [
    {
      "bufferView": 0,
      "componentType": 5126,
      "count": 24,
      "type": "VEC3",
      "max": [
        1.0,
        1.0,
        1.0
      ],
      "min": [
        -1.0,
        -1.0,
        -1.0
      ]
    },
    {
      "bufferView": 1,
      "componentType": 5126,
      "count": 24,
      "type": "VEC4",
      "max": [
        1.0,
        0.0,
        0.0,
        1.0
      ],
      "min": [
        1.0,
        0.0,
        0.0,
        1.0
      ]
    },
    {
      "bufferView": 2,
      "componentType": 5126,
      "count": 24,
      "type": "VEC3",
      "max": [
        0.0100000035,
        0.0100000035,
        0.01
      ],
      "min": [
        -0.0100000044,
        -0.0100000054,
        -0.01
      ]
    },
    {
      "bufferView": 3,
      "componentType": 5126,
      "count": 24,
      "type": "VEC3",
      "max": [
        0.0,
        0.0,
        0.0
      ],
      "min": [
        0.0,
        0.0,
        0.0
      ],
      "name": "thin"
    },
    {
      "bufferView": 4,
      "componentType": 5126,
      "count": 24,
      "type": "VEC3",
      "max": [
        0.0,
        0.01893253,
        0.0
      ],
      "min": [
        0.0,
        0.0,
        0.0
      ],
      "name": "thin"
    },
    {
      "bufferView": 5,
      "componentType": 5126,
      "count": 24,
      "type": "VEC3",
      "max": [
        0.0,
        0.0,
        0.0
      ],
      "min": [
        0.0,
        0.0,
        0.0
      ],
      "name": "thin"
    },
    {
      "bufferView": 6,
      "componentType": 5126,
      "count": 24,
      "type": "VEC3",
      "max": [
        0.0,
        0.0,
        0.0
      ],
      "min": [
        0.0,
        0.0,
        0.0
      ],
      "name": "angle"
    },
    {
      "bufferView": 7,
      "componentType": 5126,
      "count": 24,
      "type": "VEC3",
      "max": [
        0.0,
        0.0198908355,
        0.0
      ],
      "min": [
        0.0,
        0.0,
        0.0
      ],
      "name": "angle"
    },
    {
      "bufferView": 8,
      "componentType": 5126,
      "count": 24,
      "type": "VEC3",
      "max": [
        0.0,
        0.0,
        0.0
      ],
      "min": [
        0.0,
        0.0,
        0.0
      ],
      "name": "angle"
    },
    {
      "bufferView": 9,
      "componentType": 5123,
      "count": 36,
      "type": "SCALAR",
      "max": [
        23
      ],
      "min": [
        0
      ]
    },
    {
      "bufferView": 10,
      "componentType": 5126,
      "count": 127,
      "type": "SCALAR",
      "max": [
        4.19999743
      ],
      "min": [
        0.0
      ]
    },
    {
      "bufferView": 11,
      "componentType": 5126,
      "count": 254,
      "type": "SCALAR",
      "max": [
        1.0
      ],
      "min": [
        -1.52587887E-07
      ]
    }
  ],
  "asset": {
    "generator": "glTF Tools for Unity",
    "version": "2.0"
  },
  "bufferViews": [
    {
      "buffer": 0,
      "byteLength": 288
    },
    {
      "buffer": 0,
      "byteOffset": 288,
      "byteLength": 384
    },
    {
      "buffer": 0,
      "byteOffset": 672,
      "byteLength": 288
    },
    {
      "buffer": 0,
      "byteOffset": 960,
      "byteLength": 288
    },
    {
      "buffer": 0,
      "byteOffset": 1248,
      "byteLength": 288
    },
    {
      "buffer": 0,
      "byteOffset": 1536,
      "byteLength": 288
    },
    {
      "buffer": 0,
      "byteOffset": 1824,
      "byteLength": 288
    },
    {
      "buffer": 0,
      "byteOffset": 2112,
      "byteLength": 288
    },
    {
      "buffer": 0,
      "byteOffset": 2400,
      "byteLength": 288
    },
    {
      "buffer": 0,
      "byteOffset": 2688,
      "byteLength": 72
    },
    {
      "buffer": 0,
      "byteOffset": 2760,
      "byteLength": 508
    },
    {
      "buffer": 0,
      "byteOffset": 3268,
      "byteLength": 1016
    }
  ],
  "buffers": [
    {
      "uri": "AnimatedMorphCube.bin",
      "byteLength": 4284
    }
  ],
  "meshes": [
    {
      "primitives": [
        {
          "attributes": {
            "NORMAL": 0,
            "TANGENT": 1,
            "POSITION": 2
          },
          "indices": 9,
          "material": 0,
          "targets": [
            {
              "NORMAL": 3,
              "POSITION": 4,
              "TANGENT": 5
            },
            {
              "NORMAL": 6,
              "POSITION": 7,
              "TANGENT": 8
            }
          ]
        }
      ],
      "weights": [
        0.5,
        0.5
      ],
      "name": "Cube"
    }
  ],
  "materials": [
    {
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0.6038274,
          0.6038274,
          0.6038274,
          1.0
        ],
        "metallicFactor": 0.0,
        "roughnessFactor": 0.5
      },
      "name": "Material"
    }
  ],
  "nodes": [
    {
      "mesh": 0,
      "rotation": [
        0.7071068,
        0.0,
        0.0,
        0.7071067
      ],
      "scale": [
        100.0,
        100.0,
        100.0
      ],
      "name": "AnimatedMorphCube"
    }
  ],
  "scene": 0,
  "scenes": [
    {
      "nodes": [
        0
      ]
    }
  ]
}
```

**Comment by UX3D-nopper** [comment]
Also, if you touch your code, could you please change the default material?
It should be with full metallic and full roughness:
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#reference-pbrmetallicroughness

**Comment by donmccurdy** [comment]
I've opened two bugs against THREE.GLTF2Loader:

- https://github.com/mrdoob/three.js/issues/11796
- https://github.com/mrdoob/three.js/issues/11797

Is there an updated flamingo model I can test? I don't think either of those issues would prevent animation from playing.

@mrdoob the issue you saw with `THREE.PropertyBinding: Trying to update property for track: Triangle.morphTargetInfluences but it wasn't found.` was already fixed by https://github.com/mrdoob/three.js/pull/11785, I just haven't had the chance to update my viewer.

**Comment by UX3D-nopper** [comment]
Thanks a lot for investigating this.

Please get the same model running with the changes I mentioned: AnimatedMorphCube
I want to restest again, as soon as this is fixed.

Maybe/probably there is still a problem with the exporter. Just ping me, as soon as it is done.

**Comment by mrdoob** [comment]
Getting there!

![screen shot 2017-07-19 at 08 12 49](https://user-images.githubusercontent.com/97088/28374606-20a3c9cc-6c5a-11e7-8baf-6ff309cc8c23.png)

Here are the updated files:

[flamingo.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1159548/flamingo.zip) The glb file continues being 81KB regardless of what morph data is included.
[flamingo_color.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1159551/flamingo_color.zip) The glb file is now 1.8MB, I've also included a `_normals` one which is 3.2MB.

**Comment by mrdoob** [comment]
By the way, https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube plays correctly in https://gltf-viewer.donmccurdy.com/

**Comment by donmccurdy** [comment]
The first (81kb) model still does not have targets associated with the primitive/mesh:

![screen shot 2017-07-19 at 8 38 23 am](https://user-images.githubusercontent.com/1848368/28375975-cfda0142-6c5d-11e7-8bec-896777b84b61.png)

I've opened PRs to address the other two issues, and will update my viewer later tonight. Thanks!

**Comment by UX3D-nopper** [comment]
Regarding this the model:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube 
It works in both engines.

But as soon as the animation is removed and the weights are modified, I just works fine on my engine but not on three,js

I want to investigate the problem step by step.

**Comment by UX3D-nopper** [comment]
I'll check the first flamingo meanwhile.

**Comment by UX3D-nopper** [comment]
Okay, found the problem and have a fix for the flamingo. Will upload after the call.

**Comment by UX3D-nopper** [comment]
Okay, the shape keys do collide with auto smooth during export. As morph targets are more important - and the mesh can be modified for having the same effect - in this case the exporter disables auto smooth.
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/abf5058d8af99b3e3da5467b8abb5d92f84b1ec3

Now both Flamingos can be exported, but in both cases the animation is not used.

So, let's keep the plan and try to solve the problem in three.js with AnimatedMorphCube, when animations are removed and the mesh weights are set.

If this is solved, please ping me and then we investigate, why the animations do not work.

**Comment by UX3D-nopper** [comment]
The auto smooth with shape key collision - this will be a larger task. Will go back to this, as soon as this morphing problem is 100% solved.

**Comment by mrdoob** [comment]
Okay, updated files:

[flamingo.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1160085/flamingo.zip) The glb file is now 345KB. Animations still don't play, but is likely to be the loader.

![screen shot 2017-07-19 at 11 33 00](https://user-images.githubusercontent.com/97088/28383476-1e35e23a-6c76-11e7-8a18-620ea0036b33.png)

[flamingo_color.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1160095/flamingo_color.zip) The glb stays at 1.8MB, the animation is still broken.

![screen shot 2017-07-19 at 11 34 11](https://user-images.githubusercontent.com/97088/28383556-5f477bbc-6c76-11e7-8b99-d60b8dfedc99.png)

**Comment by donmccurdy** [comment]
^Looks better! Both of the errors above should be resolved when I update the viewer to use the latest version of GLTF2Loader, so I will post an update here when that is done later today.

**Comment by UX3D-nopper** [comment]
Okay, before we go back to the Flamingo, can you guys test these two files - exporting with and without animations?

https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scenes/01_morphed_triangle.blend
https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scenes/01_morphed_cube.blend

Do you get the same result as seen in Blender?

If not, what I assume, can you tell me exactly why? Especially the triangle can be debugged easily.

**Comment by donmccurdy** [comment]
I've bumped my viewer to latest GLTF2Loader, and the morph targets for both flamingos look reasonable:

![10682a08-6e9c-4088-94c2-1b717245c7ef-32320-000276d8c5b3933e](https://user-images.githubusercontent.com/1848368/28396146-5d0e59a0-6cae-11e7-865d-cc7651ea37f3.gif)

Also, both of your test models look work @UX3D-nopper. I only had to disable materials before export, or I saw an error (probably I just needed to link in some node group?). There are now playback controls for morph targets in the viewer, if you want to test this.

**Comment by UX3D-nopper** [comment]
Great!
The glitch is because all animations were exported. I have added a feature, where it is now possible to export only withing the playback range:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/4c811994ddadff3899b0f7dd392f0c929fc241fe
This fixes the animation glitch.

Hmm, the morphing examples are using the included node group and probably this was broken.

**Comment by UX3D-nopper** [comment]
Yes, thats the problem.

**Comment by UX3D-nopper** [comment]
Can you just open the morphing file at its location and export from there? It is important, that the relative path to the PBR node is not broken.

I will close this, as from my side, this morphing problem seems to be fixed.

**Comment by mrdoob** [comment]
Nice work guys!

**Comment by mrdoob** [comment]
I can still see a 1-frame glitch in the animation though. I'll investigate...

**Comment by UX3D-nopper** [comment]
Which Flamingo - I just exported the colored flamingo and dropped it into Don's viewer. Cant see it. Which frame?

**Comment by UX3D-nopper** [comment]
Also both - cant see the glitch. Have u updated to latest exporter and exported again?

**Comment by mrdoob** [comment]
It's very hard to see. I think it's basically not a clean loop. Like the last frame not staying long enough (loader/player at fault probably).

**Comment by UX3D-nopper** [comment]
Okay, please get back to me if u see a problem with te export.

**Comment by mrdoob** [comment]
Okay, it may be an issue with the exporter...

Seems like the start frame of the animation range is ignored, it always start from 0. Here's a file where I've moved the keyframes and then set the animation frame to 11-31. 

Should the keyframes be translated based on the frame_start at export time? Or is the frame_start information included in the gltf and the loader/player is not using it?

[owl.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1163830/owl.zip)

**Comment by mrdoob** [comment]
If I move the keyframes so it goes from 0-20 everything looks good 👌 [owl_good.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1163882/owl_good.zip) 

Unfortunately, Blender's default start frame is 1. We should probably address this.

**Comment by UX3D-nopper** [comment]
Let me fix this.

**Comment by UX3D-nopper** [comment]
Okay, fixed it here:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/1de0693d621c4c4b98800590cd303bc7e170328e

But I am thinking about the impact and if this whould be specieifed somewhere. Needs the engine to offset the values or the exporter?

**Comment by UX3D-nopper** [comment]
My engine did behave exactly the same like yours. And it is valid glTF animation data:

> The index of an accessor containing keyframe input values, e.g., time. That accessor must have componentType FLOAT. The values represent time in seconds with time[0] >= 0.0, and strictly increasing values, i.e., time[n + 1] > time[n].

**Comment by UX3D-nopper** [comment]
Actually it is a bug in both engines. I will upload a new version, where the keyframes "moving" is an option.

**Comment by UX3D-nopper** [comment]
I keep the adjustment of the keyframes as default, as I assume others will habe the same issue as well.

**Comment by mrdoob** [comment]
Thank you!
